# Tensors with basic operations


In [1]:
import torch
torch.__version__

'2.4.1+cu121'

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [4]:
print(f'scalar: {scalar.ndim}')
print(f'vector: {vector.ndim}')

scalar: 0
vector: 1


In [5]:
print(f'scalar: {scalar.shape}')
print(f'vector: {vector.shape}')


scalar: torch.Size([])
vector: torch.Size([2])


# Matrix




In [6]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
MATRIX.ndim

2

In [8]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.8918, 0.9871, 0.2536, 0.8223],
         [0.2236, 0.1233, 0.6294, 0.5173],
         [0.1747, 0.5849, 0.5772, 0.1195]]),
 torch.float32)

In [9]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [10]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.6980, 0.8612, 0.6653, 0.5267],
        [0.5392, 0.9101, 0.8754, 0.2308],
        [0.1955, 0.1831, 0.7065, 0.0337]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [11]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
tensor = torch.tensor([1, 2, 3])
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [12]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 835 µs, sys: 962 µs, total: 1.8 ms
Wall time: 4.91 ms


tensor(14)

In [13]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 0 ns, sys: 1.52 ms, total: 1.52 ms
Wall time: 12.8 ms


tensor(14)