# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)
!nvidia-smi

Wed Oct 16 19:07:11 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   65C    P8              13W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Create a random tensor with shape `(7, 7)`.


In [6]:
# Import torch
import torch,numpy as np
# Create random tensor

torch.device ='cuda' if torch.cuda.is_available() else 'cpu'
print(torch.device)
random_tensor=torch.rand(1,5,3)
print(random_tensor)
numpy_tensor=torch.tensor(np.array([[1,2,3],[4,5,6]]))
print(numpy_tensor)
print()
# Create random tensor
numpy_tensor.shape
random_tensor.shape
# Count number of devices
torch.cuda.device_count()


cuda
tensor([[[0.1361, 0.1403, 0.8187],
         [0.7028, 0.1808, 0.2801],
         [0.0867, 0.5748, 0.3899],
         [0.0802, 0.9232, 0.4003],
         [0.4830, 0.4998, 0.4867]]])
tensor([[1, 2, 3],
        [4, 5, 6]])



1

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [14]:
# Create another random tensor and check the device or out the tensor to cuda


# print(random_tensor, random_tensor.device)
# random_tensor=random_tensor.to(device='cuda')
# print(random_tensor, random_tensor.device)

# print(numpy_tensor, numpy_tensor.device)
# Perform matrix multiplication
rand_tensorA=torch.rand(7,7)
rand_tensorB=torch.rand(1,7)

torch.matmul(rand_tensorA,rand_tensorB.T)



tensor([[2.1331],
        [1.9338],
        [2.1844],
        [1.5032],
        [1.9408],
        [1.2924],
        [1.5643]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [23]:
# Set manual seed
torch.manual_seed(1)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape


(tensor([[2.1819],
         [2.1090],
         [2.0406],
         [2.1226],
         [1.3201],
         [2.1429],
         [2.1000]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [24]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [49]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)
tensor_A, tensor_B


Device: cuda


(tensor([[0.9544, 0.9371, 0.2165],
         [0.9892, 0.6237, 0.1679]], device='cuda:0'),
 tensor([[0.7737, 0.1267, 0.9620],
         [0.1786, 0.6414, 0.6523]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [51]:
# Perform matmul on tensor_A and tensor_B
tensor_c=torch.matmul(tensor_A,tensor_B.T)
print(tensor_c, tensor_c.shape)

tensor([[1.0654, 0.9127],
        [1.0059, 0.6862]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [54]:
# Find max
print(tensor_c.max())

# Find min
print(tensor_c.min())

tensor(1.0654, device='cuda:0')
tensor(0.6862, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [55]:
# Find arg max
print(tensor_c.argmax())

# Find arg min
print(tensor_c.argmin())

tensor(0, device='cuda:0')
tensor(3, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [56]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
